# Generated by Django 4.0.4 on 2022-05-04 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NamePeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalCharac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=10)),
                ('mass', models.CharField(max_length=10)),
                ('hair_color', models.CharField(max_length=10)),
                ('namePeople', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.namepeople')),
            ],
        ),
    ]
